# Generated by Django 5.2 on 2025-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='story',
            name='published_at',
        ),
        migrations.AlterField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/300x200'),
            preserve_default=False,
        ),
    ]
